// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75pJqdvaqsFk5Qma_IhepyzDKFi1iIeU',
    appId: '1:1026738841199:web:d6572c4bab74d220418f9a',
    messagingSenderId: '1026738841199',
    projectId: 'chatbot-f5969',
    authDomain: 'chatbot-f5969.firebaseapp.com',
    storageBucket: 'chatbot-f5969.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3-5AerWKZgqTUkfX2-DDVIePzyfyeOo',
    appId: '1:1026738841199:android:4c8914b89d507a8d418f9a',
    messagingSenderId: '1026738841199',
    projectId: 'chatbot-f5969',
    storageBucket: 'chatbot-f5969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmNW30vVPu8WXV6BJvKa2FI7jDUpxggE',
    appId: '1:1026738841199:ios:b2ee1b34731039aa418f9a',
    messagingSenderId: '1026738841199',
    projectId: 'chatbot-f5969',
    storageBucket: 'chatbot-f5969.firebasestorage.app',
    iosBundleId: 'com.example.hotelAssistant',
  );
}
